"""
This module was autogenerated by gale.
"""
import settings
from src.my_game import MyGame

if __name__ == '__main__':
    game = MyGame(
        "My Game",
        settings.WINDOW_WIDTH, settings.WINDOW_HEIGHT,
        settings.VIRTUAL_WIDTH, settings.VIRTUAL_HEIGHT
    )
    game.exec()
